-- assignment 2
--q1------

-- CREATE TABLE PERSONEL(
--   NAME VARCHAR2(20),
--   ROLLNO NUMBER(3),
--   ADDRESS VARCHAR2(3),
--   SCORE NUMBER(5),
--   PRIMARY KEY(ROLLNO),
--   CONSTRAINT CHK_LEN_ADDRESS CHECK (lENGTH(ADDRESS) = 3)
-- );
-- INSERT INTO PERSONEL VALUES('AYAN',1,'KOL',1234);
-- INSERT INTO PERSONEL VALUES('NIKHIL',2,'KOL',2134);
-- INSERT INTO PERSONEL VALUES('RAJAT',3,'DEL',4321);
-- INSERT INTO PERSONEL VALUES('AJAY',4,'DEL',1122);
-- INSERT INTO PERSONEL VALUES('MRINAL',5,'KOL',1212);

--q2*************

-- CREATE TABLE RESULT(
-- ROLLNO NUMBER,
-- MARKS NUMBER(10),
-- SUB VARCHAR2(20),
-- CONSTRAINT FK_ROLLNO FOREIGN KEY (ROLLNO) REFERENCES PERSONEL(ROLLNO)
-- );

-- INSERT INTO RESULT VALUES (1, 90, 'DBMS');
-- INSERT INTO RESULT VALUES (1, 88, 'GRAPHICS');
-- INSERT INTO RESULT VALUES (2, 89, 'DBMS');
-- INSERT INTO RESULT VALUES (2, 95, 'GRAPHICS');
-- INSERT INTO RESULT VALUES (3, 99, 'DBMS');
-- INSERT INTO RESULT VALUES (3, 98, 'GRAPHICS');
-- INSERT INTO RESULT VALUES (4, 82, 'DBMS');
-- INSERT INTO RESULT VALUES (4, 79, 'GRAPHICS');
-- INSERT INTO RESULT VALUES (5, 92, 'DBMS');
-- INSERT INTO RESULT VALUES (5, 75, 'GRAPHICS');

-- q3*************
-- select personel details

-- SELECT * FROM PERSONEL;

-- 4)	SELECT PERSONAL DETAILS FOR THOSE STUDENTS WHO LIVE IN ‘KOL’

-- SELECT * FROM PERSONEL WHERE ADDRESS ='KOL';

-- 5)	SELECT PERSONAL DETAILS FOR THOSE STUDENTS WHOSE NAME STARTS WITH ‘A’

  -- SELECT * FROM PERSONEL WHERE NAME LIKE 'A%';

  -- 6)	SELECT PERSONAL DETAILS WHERE NAME IS OF ATLEAST 5 CHARACTERS LONG.


   -- SELECT * FROM PERSONEL WHERE LENGTH(NAME) >= 5;

  --  7)	SELECT PERSONAL DETAILS OF STUDENT, HAVING MAXUMUM SCORE

    -- SELECT * FROM PERSONEL WHERE SCORE = (SELECT MAX(SCORE) FROM PERSONEL);
    -- 8)	PRINT TOTAL NUMBER OF STUDENTS
    -- SELECT COUNT(*) AS TOTAL_STUDENTS FROM PERSONEL;

-- 9)	SELECT NAME,ROLLNO,MARKS AND SUB FOR ALL THE STUDENTS
  -- SELECT P.NAME,P.ROLLNO,R.MARKS,R.SUB FROM PERSONEL P JOIN RESULT R ON P.ROLLNO = R.ROLLNO;

  -- SELECT P.NAME, P.ROLLNO, (SELECT R.MARKS FROM RESULT R WHERE R.ROLLNO = P.ROLLNO) AS MARKS, (SELECT R.SUB FROM RESULT R WHERE R.ROLLNO = P.ROLLNO) AS SUB FROM PERSONEL P; -- USING SUBQUERY
  -- 10)	SELECT THE NAME OF ALL  STUDENTS WITH THEIR TOTAL MARKS
  -- SELECT P.NAME, SUM(R.MARKS) AS TOTAL_MARKS FROM PERSONEL P JOIN RESULT R ON P.ROLLNO = R.ROLLNO GROUP BY P.NAME;

  -- 11)	SELECT THE NAME AND TOTAL MARKS OF THAT STUDENT WHO HAS THE HIGHEST TOTAL
  -- SELECT P.NAME,SUM(R.MARKS) AS TOTAL_MARKS FROM PERSONEL P JOIN RESULT R ON P.ROLLNO = R.ROLLNO GROUP BY P.NAME ORDER BY TOTAL_MARKS DESC FETCH FIRST 1 ROWS ONLY;

  SELECT P.NAME , SUM(R.MARKS) AS TOTAL_MARKS FROM PERSONEL P JOIN RESULT R ON P.ROLLNO = R.ROLLNO GROUP BY P.NAME
  HAVING SUM(R.MARKS) =(
    SELECT MAX(TOTAL) FROM(
      SELECT SUM(MARKS) AS TOTAL FROM RESULT
      GROUP BY ROLLNO
    )
  );