SET SERVEROUTPUT ON;
SET VERIFY OFF;

ACCEPT num NUMBER PROMPT 'ENTER A NUMBER...  ';

DECLARE
n NUMBER := &num;


BEGIN
  -- for i IN 1..n LOOP
  --   DBMS_OUTPUT.PUT_LINE('THE NUMBER IS '||i);
  -- END LOOP;

FOR i IN 1..n LOOP
  IF (MOD(i,2) = 0) THEN
    DBMS_OUTPUT.PUT_LINE('THE NUMBER IS '||i);

  ELSIF (MOD(i,2)=1) THEN
    DBMS_OUTPUT.PUT_LINE('THE NUMBER IS '||i);
  END IF;

END LOOP;
END;
/